import time

t= time()
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")
print("asdfasdfasdfasddddddddd")

t2= time()

t3=(t2-t)*1000
print(t,t2,t3)